name = "WFAR"
prefix = "wfar"
author = "Walthzer/Shark"
check = [
    "!binarizer_link"
]
files = [
    "*.so",
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_wfar_ca.paa",
    "meta.cpp"
]
exclude = [
    "*.psd",
    "*.png",
    "*.xcf",
    "*.ssa",
    "*.blend1",
    "*.obj",
    "*.blend",
    "*.mtl",
    "*.svg",
    "*.txt"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip wfar_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"

# Binarizer file search compatibility
[scripts.binarizer_link]
steps_windows = [
    "if not exist z\\wfar mkdir z\\wfar",
    "if not exist z\\wfar\\addons mklink /j z\\wfar\\addons addons",
    "if not exist a3 mklink /j a3 N:\\Arma3Pdrive\\a3"
]