PREP(convertToBuildSite);
PREP(cutGrass);
PREP(getObjectBounding2D);
PREP(getScaffoldingPositions);
PREP(moveScaffolding);
PREP(playerHandelBuilding);
PREP(playerHandelRemoving);
//PREP(createProgressBar);
PREP(getSurfaceHeightASL);
