name = "WFAR"
mainprefix = "z"
prefix = "wfar"
author = "Walthzer/Shark"
check = [
    "!binarizer_link"
]

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_wfar_ca.paa",
    "meta.cpp"
]
exclude = [
    "*.psd",
    "*.png",
    "*.xcf",
    "*.ssa",
    "*.blend1",
    "*.obj",
    "*.blend",
    "*.mtl",
    "*.svg",
    "*.txt"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip wfar_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"

# Binarizer file search compatibility
[scripts.binarizer_link]
steps_windows = [
    "if not exist z\\wfar mkdir z\\wfar",
    "if not exist z\\wfar\\addons mklink /j z\\wfar\\addons addons",
    "if not exist a3 mklink /j a3 N:\\Arma3Pdrive\\a3"
]

# Launched with `hemtt launch ace
[hemtt.launch.wfar_slim]
workshop = [
    "463939057", # ACE3's Workshop ID
    "1779063631", # ZEN's ID
    "450814997", # CBA's ID
]

# Launched with `hemtt launch wfar
[hemtt.launch.wfar]
presets = [
    "WFAR9", # .html presets from .hemtt/presets/
]